#!/bin/sh

NAME="PWM"

start() {
    echo -n "Starting $NAME:"
    echo " OK"
}

stop() {
    echo -n "Stopping $NAME: "
    echo " OK"
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	sleep 0.5
	start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
